server:
  port: 5088
  compression:
    enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_test
    username: root
    password: pw1234
mybatis:
  mapper-locations: classpath:mybatis/*.xml  # 注意:一定要对应mapper映射xml文件的所在路径
  type-aliases-package: us.bojie.springdemo.entity  # 注意:对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true # 数据库字段下划线自动转驼峰
